workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      xcode_scheme: "Runner"
      vars:
        BUNDLE_ID: "com.leboneng.mathletics"  # <-- change this to match your app
      groups:
        - app_store_credentials   # <-- set these in Codemagic UI
        - signing_credentials     # <-- set these in Codemagic UI
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build IPA
        script: |
          flutter build ipa -t lib/main.dart  # <== using your actual entry point
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        bundle_id: $BUNDLE_ID
